version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./dataMongo:/data/db

  myapp:
    image: my_app/node
    container_name: myapp
    restart: always
    ports:
            - 4000:4000
    volumes:
      - ./graphql:/data
